import type { Requirement } from '../requirements/Requirement';

/**
 * Grupo al que pertenece un logro. Solo sirve para pintarlos ordenados: con
 * cincuenta en una sola rejilla no se encontraba nada.
 */
export type AchievementGroup =
  | 'primeros'
  | 'mineria'
  | 'combate'
  | 'jefes'
  | 'pueblo'
  | 'eventos'
  | 'lunar'
  | 'fortuna';

/**
 * Rareza. Decide el color del marco y el tamano de la recompensa, para que un
 * logro de bronce y uno de oro no se lean igual de un vistazo.
 */
export type AchievementTier = 'bronce' | 'plata' | 'oro';

export interface AchievementDef {
  id: string;
  name: string;
  description: string;
  /** Sprite del icono. */
  icon: string;
  group: AchievementGroup;
  tier: AchievementTier;
  requirement: Requirement;
  /** Recompensa en cobre al conseguirlo. */
  coins: number;
}

export const GROUP_LABEL: Record<AchievementGroup, string> = {
  primeros: 'Primeros pasos',
  mineria: 'Mineria y crafteo',
  combate: 'Combate',
  jefes: 'Jefes',
  pueblo: 'El pueblo',
  eventos: 'Invasiones',
  lunar: 'Evento lunar',
  fortuna: 'Fortuna y rarezas',
};

export const GROUP_ORDER: AchievementGroup[] = [
  'primeros',
  'mineria',
  'combate',
  'jefes',
  'pueblo',
  'eventos',
  'lunar',
  'fortuna',
];

/**
 * Logros, con los nombres guinando a los reales de Terraria.
 *
 * Los iconos son las **ilustraciones reales de los logros de Terraria**
 * (`public/assets/achievements`), no sprites de objetos. Con sprites la pantalla
 * parecia un inventario descolocado: dos logros distintos podian llevar el mismo
 * pico y no se distinguian de un vistazo. Cada uno usa el icono del logro
 * equivalente del juego, o el que mas se le parece cuando no existe.
 */
export const AchievementList: AchievementDef[] = [
  // ---------------------------------------------------------------- primeros pasos
  {
    id: 'first_swing',
    name: 'Cortar madera',
    description: 'Rompe tu primer nodo.',
    icon: 'Achievement_Timber!!',
    group: 'primeros',
    tier: 'bronce',
    requirement: { kind: 'nodesBroken', amount: 1 },
    coins: 100,
  },
  {
    id: 'benched',
    name: 'Fabricante novato',
    description: 'Fabrica una mesa de trabajo.',
    icon: 'Achievement_Benched',
    group: 'primeros',
    tier: 'bronce',
    requirement: { kind: 'itemDiscovered', itemId: 'Work_Bench' },
    coins: 300,
  },
  {
    id: 'ooo_shiny',
    name: 'Que brillante',
    description: 'Extrae tu primer mineral de cobre.',
    icon: 'Achievement_Ooo!_Shiny!',
    group: 'primeros',
    tier: 'bronce',
    requirement: { kind: 'itemGathered', itemId: 'Copper_Ore', amount: 1 },
    coins: 200,
  },
  {
    id: 'hot_hot_hot',
    name: 'Que calor',
    description: 'Fabrica un horno.',
    icon: "Achievement_I'm_Smelting!",
    group: 'primeros',
    tier: 'bronce',
    requirement: { kind: 'itemDiscovered', itemId: 'Furnace' },
    coins: 500,
  },
  {
    id: 'heavy_metal',
    name: 'Heavy metal',
    description: 'Fabrica un yunque de hierro.',
    icon: 'Achievement_Heavy_Metal',
    group: 'primeros',
    tier: 'bronce',
    requirement: { kind: 'itemDiscovered', itemId: 'Iron_Anvil' },
    coins: 800,
  },
  {
    id: 'star_material',
    name: 'Material estelar',
    description: 'Funde tu primer lingote de meteorito.',
    icon: 'Achievement_Extra_Shiny!',
    group: 'primeros',
    tier: 'plata',
    requirement: { kind: 'itemDiscovered', itemId: 'Meteorite_Bar' },
    coins: 12000,
  },

  // ---------------------------------------------------------------- mineria
  {
    id: 'stop_hammer_time',
    name: 'Picador constante',
    description: 'Rompe 250 nodos.',
    icon: 'Achievement_Stop!_Hammer_Time!',
    group: 'mineria',
    tier: 'bronce',
    requirement: { kind: 'nodesBroken', amount: 250 },
    coins: 1500,
  },
  {
    id: 'miner_for_fire',
    name: 'Minero profesional',
    description: 'Rompe 1000 nodos.',
    icon: 'Achievement_Miner_for_Fire',
    group: 'mineria',
    tier: 'plata',
    requirement: { kind: 'nodesBroken', amount: 1000 },
    coins: 6000,
  },
  {
    id: 'excavator',
    name: 'Excavadora',
    description: 'Rompe 10000 nodos.',
    icon: 'Achievement_Bulldozer',
    group: 'mineria',
    tier: 'oro',
    requirement: { kind: 'nodesBroken', amount: 10_000 },
    coins: 250_000,
  },
  {
    id: 'clicker',
    name: 'Dedo de acero',
    description: 'Haz 1000 clicks.',
    icon: 'Achievement_Running_Man',
    group: 'mineria',
    tier: 'bronce',
    requirement: { kind: 'clicks', amount: 1000 },
    coins: 1200,
  },
  {
    id: 'clicker_pro',
    name: 'Dedo de titanio',
    description: 'Haz 25000 clicks.',
    icon: 'Achievement_Marathon_Medalist',
    group: 'mineria',
    tier: 'oro',
    requirement: { kind: 'clicks', amount: 25_000 },
    coins: 120_000,
  },
  {
    id: 'pickaxe_65',
    name: 'Rompe-ebonita',
    description: 'Consigue un pico de potencia 65.',
    icon: 'Achievement_Begone,_Evil!',
    group: 'mineria',
    tier: 'plata',
    requirement: { kind: 'pickPower', amount: 65 },
    coins: 8000,
  },
  {
    id: 'molten_power',
    name: 'Potencia 100',
    description: 'Fabrica el pico fundido.',
    icon: "Achievement_It's_Getting_Hot_in_Here",
    group: 'mineria',
    tier: 'plata',
    requirement: { kind: 'pickPower', amount: 100 },
    coins: 70_000,
  },
  {
    id: 'chlorophyte_power',
    name: 'Potencia 200',
    description: 'Consigue un pico que abra la clorofita y el Templo.',
    icon: 'Achievement_Drax_Attax',
    group: 'mineria',
    tier: 'oro',
    requirement: { kind: 'pickPower', amount: 200 },
    coins: 200_000,
  },
  {
    id: 'luminite_power',
    name: 'Potencia 225',
    description: 'Fabrica uno de los cuatro picos de luminita. No hay nada mas arriba.',
    icon: 'Achievement_Terrarist',
    group: 'mineria',
    tier: 'oro',
    requirement: { kind: 'pickPower', amount: 225 },
    coins: 1_000_000,
  },
  {
    id: 'hell_and_back',
    name: 'Ida y vuelta al infierno',
    description: 'Extrae tu primera piedra infernal.',
    icon: 'Achievement_To_Hell_and_Back',
    group: 'mineria',
    tier: 'plata',
    requirement: { kind: 'itemGathered', itemId: 'Hellstone', amount: 1 },
    coins: 20_000,
  },
  {
    id: 'temple_raider',
    name: 'Saqueador del Templo',
    description: 'Pica 100 ladrillos lihzahrd.',
    icon: 'Achievement_Temple_Raider',
    group: 'mineria',
    tier: 'oro',
    requirement: { kind: 'itemGathered', itemId: 'Lihzahrd_Brick', amount: 100 },
    coins: 300_000,
  },
  {
    id: 'night_edge',
    name: 'La espada definitiva',
    description: 'Forja el Filo Nocturno en un altar demoniaco.',
    icon: 'Achievement_Crafty',
    group: 'mineria',
    tier: 'plata',
    requirement: { kind: 'itemDiscovered', itemId: "Night's_Edge" },
    coins: 90_000,
  },
  {
    id: 'terra_blade',
    name: 'Hoja de la tierra',
    description: 'Forja la Terra Blade juntando las dos hojas verdaderas.',
    icon: 'Achievement_Sword_of_the_Hero',
    group: 'mineria',
    tier: 'oro',
    requirement: { kind: 'itemDiscovered', itemId: 'Terra_Blade' },
    coins: 400_000,
  },
  {
    id: 'zenith',
    name: 'Cenit',
    description: 'Junta las diez espadas y forja el Cenit. Ya esta, no hay mas.',
    icon: 'Achievement_Infinity_+1_Sword',
    group: 'mineria',
    tier: 'oro',
    requirement: { kind: 'itemDiscovered', itemId: 'Zenith' },
    coins: 5_000_000,
  },

  // ---------------------------------------------------------------- combate
  {
    id: 'slime_time',
    name: 'Hora del slime',
    description: 'Derrota a 50 enemigos.',
    icon: 'Achievement_Slimer',
    group: 'combate',
    tier: 'bronce',
    requirement: { kind: 'enemiesDefeated', amount: 50 },
    coins: 1000,
  },
  {
    id: 'exterminator',
    name: 'Exterminador',
    description: 'Derrota a 2000 enemigos.',
    icon: 'Achievement_Exterminator',
    group: 'combate',
    tier: 'plata',
    requirement: { kind: 'enemiesDefeated', amount: 2000 },
    coins: 80_000,
  },
  {
    id: 'eye_on_you',
    name: 'Te tiene fichado',
    description: 'Consigue una lente de un ojo demoniaco.',
    icon: 'Achievement_Eye_on_You',
    group: 'combate',
    tier: 'bronce',
    requirement: { kind: 'itemGathered', itemId: 'Lens', amount: 1 },
    coins: 400,
  },
  {
    id: 'bonehead',
    name: 'Coleccionista de huesos',
    description: 'Recoge 250 huesos.',
    icon: 'Achievement_Robbing_the_Grave',
    group: 'combate',
    tier: 'plata',
    requirement: { kind: 'itemGathered', itemId: 'Bone', amount: 250 },
    coins: 15_000,
  },
  {
    id: 'jungle_explorer',
    name: 'Explorador de la jungla',
    description: 'Recoge 50 esporas de jungla.',
    icon: 'Achievement_Jeepers_Creepers',
    group: 'combate',
    tier: 'bronce',
    requirement: { kind: 'itemGathered', itemId: 'Jungle_Spores', amount: 50 },
    coins: 9000,
  },
  {
    id: 'full_heart',
    name: 'Corazon lleno',
    description: 'Consigue los 15 cristales de vida: 400 PV.',
    icon: 'Achievement_Heart_Breaker',
    group: 'combate',
    tier: 'plata',
    requirement: { kind: 'itemGathered', itemId: 'Life_Crystal', amount: 15 },
    coins: 60_000,
  },
  {
    id: 'life_fruit',
    name: 'Fruta prohibida',
    description: 'Recoge 20 frutas de vida: el maximo del juego.',
    icon: 'Achievement_Topped_Off',
    group: 'combate',
    tier: 'oro',
    requirement: { kind: 'itemGathered', itemId: 'Life_Fruit', amount: 20 },
    coins: 350_000,
  },

  // ---------------------------------------------------------------- jefes
  {
    id: 'gelatin_world_tour',
    name: 'Gira mundial de gelatina',
    description: 'Derrota al Rey Slime.',
    icon: 'Achievement_Gelatin_World_Tour',
    group: 'jefes',
    tier: 'bronce',
    requirement: { kind: 'bossDefeated', bossId: 'king_slime' },
    coins: 5000,
  },
  {
    id: 'eye_of_cthulhu_down',
    name: 'Ojo por ojo',
    description: 'Derrota al Ojo de Cthulhu.',
    icon: 'Achievement_An_Eye_For_An_Eye',
    group: 'jefes',
    tier: 'bronce',
    requirement: { kind: 'bossDefeated', bossId: 'eye_of_cthulhu' },
    coins: 10_000,
  },
  {
    id: 'worm_fear',
    name: 'Miedo a los gusanos',
    description: 'Derrota al Devorador de Mundos.',
    icon: 'Achievement_Worm_Fodder',
    group: 'jefes',
    tier: 'plata',
    requirement: { kind: 'bossDefeated', bossId: 'eater_of_worlds' },
    coins: 25_000,
  },
  {
    id: 'queen_bee_down',
    name: 'Miel amarga',
    description: 'Derrota a la Abeja Reina.',
    icon: 'Achievement_Sting_Operation',
    group: 'jefes',
    tier: 'plata',
    requirement: { kind: 'bossDefeated', bossId: 'queen_bee' },
    coins: 30_000,
  },
  {
    id: 'skeletron_down',
    name: 'Sin manos',
    description: 'Derrota a Esqueletron y abre la Mazmorra.',
    icon: 'Achievement_Boned',
    group: 'jefes',
    tier: 'plata',
    requirement: { kind: 'bossDefeated', bossId: 'skeletron' },
    coins: 60_000,
  },
  {
    id: 'wall_of_flesh_down',
    name: 'El otro lado',
    description: 'Derrota al Muro de Carne. Fin del pre-Hardmode.',
    icon: 'Achievement_Still_Hungry',
    group: 'jefes',
    tier: 'oro',
    requirement: { kind: 'bossDefeated', bossId: 'wall_of_flesh' },
    coins: 150_000,
  },
  {
    id: 'mechanical_down',
    name: 'Chatarra',
    description: 'Derrota al Destructor.',
    icon: 'Achievement_Buckets_of_Bolts',
    group: 'jefes',
    tier: 'oro',
    requirement: { kind: 'bossDefeated', bossId: 'the_destroyer' },
    coins: 200_000,
  },
  {
    id: 'plantera_down',
    name: 'Jardineria agresiva',
    description: 'Derrota a Plantera y consigue la llave del Templo.',
    icon: 'Achievement_The_Great_Southern_Plantkill',
    group: 'jefes',
    tier: 'oro',
    requirement: { kind: 'bossDefeated', bossId: 'plantera' },
    coins: 400_000,
  },
  {
    id: 'golem_down',
    name: 'Piedra contra piedra',
    description: 'Derrota a Golem en el Templo Lihzahrd.',
    icon: 'Achievement_Lihzahrdian_Idol',
    group: 'jefes',
    tier: 'oro',
    requirement: { kind: 'bossDefeated', bossId: 'golem' },
    coins: 600_000,
  },

  // ---------------------------------------------------------------- pueblo
  {
    id: 'first_house',
    name: 'Hogar, dulce hogar',
    description: 'Construye tu primera casa y mete al Guia dentro.',
    icon: 'Achievement_No_Hobo',
    group: 'pueblo',
    tier: 'bronce',
    requirement: { kind: 'npcsHoused', amount: 1 },
    coins: 2000,
  },
  {
    id: 'town_five',
    name: 'Esto ya es un pueblo',
    description: 'Ten cinco vecinos viviendo contigo.',
    icon: 'Achievement_Home_Sweet_Home',
    group: 'pueblo',
    tier: 'plata',
    requirement: { kind: 'npcsHoused', amount: 5 },
    coins: 25_000,
  },
  {
    id: 'goblin_friend',
    name: 'Amigo de los duendes',
    description: 'Mete al Inventor duende en una casa: es el unico que reforja.',
    icon: 'Achievement_Goblin_Punter',
    group: 'pueblo',
    tier: 'plata',
    requirement: { kind: 'npcHoused', npcId: 'goblin_tinkerer' },
    coins: 40_000,
  },
  {
    id: 'town_twelve',
    name: 'Alcalde',
    description: 'Ten doce vecinos.',
    icon: 'Achievement_Leading_Landlord',
    group: 'pueblo',
    tier: 'oro',
    requirement: { kind: 'npcsHoused', amount: 12 },
    coins: 300_000,
  },
  {
    id: 'taxman',
    name: 'Renta pasiva',
    description: 'Mete al Recaudador en una casa.',
    icon: 'Achievement_Good_Little_Slave',
    group: 'pueblo',
    tier: 'oro',
    requirement: { kind: 'npcHoused', npcId: 'tax_collector' },
    coins: 500_000,
  },
  {
    id: 'town_full',
    name: 'No cabe uno mas',
    description: 'Ten a los 25 vecinos en el pueblo.',
    icon: 'Achievement_Real_Estate_Agent',
    group: 'pueblo',
    tier: 'oro',
    requirement: { kind: 'npcsHoused', amount: 25 },
    coins: 3_000_000,
  },

  // ---------------------------------------------------------------- invasiones
  {
    id: 'goblin_army',
    name: 'Y tu que ejercito',
    description: 'Repele el Ejercito de duendes.',
    icon: 'Achievement_You_and_What_Army',
    group: 'eventos',
    tier: 'plata',
    requirement: { kind: 'invasionCleared', invasionId: 'goblin_army' },
    coins: 30_000,
  },
  {
    id: 'frost_legion_down',
    name: 'Quieres matar a un muneco de nieve',
    description: 'Repele la Legion de escarcha.',
    icon: 'Achievement_Do_You_Want_to_Slay_a_Snowman',
    group: 'eventos',
    tier: 'plata',
    requirement: { kind: 'invasionCleared', invasionId: 'frost_legion' },
    coins: 120_000,
  },
  {
    id: 'eclipse_down',
    name: 'Heliofobia',
    description: 'Sobrevive a un Eclipse solar y tumba a Mothron.',
    icon: 'Achievement_Heliophobia',
    group: 'eventos',
    tier: 'oro',
    requirement: { kind: 'invasionCleared', invasionId: 'solar_eclipse' },
    coins: 300_000,
  },
  {
    id: 'frost_moon_down',
    name: 'Grito de hielo',
    description: 'Aguanta la Luna de escarcha entera y tumba a la Reina de Hielo.',
    icon: 'Achievement_Ice_Scream',
    group: 'eventos',
    tier: 'oro',
    requirement: { kind: 'invasionCleared', invasionId: 'frost_moon' },
    coins: 800_000,
  },
  {
    id: 'martian_down',
    name: 'Gorro de papel de aluminio',
    description: 'Repele la Locura marciana y derriba el platillo.',
    icon: 'Achievement_Tin-Foil_Hatter',
    group: 'eventos',
    tier: 'oro',
    requirement: { kind: 'invasionCleared', invasionId: 'martian_madness' },
    coins: 1_200_000,
  },
  {
    id: 'all_invasions',
    name: 'Verdugo de mundos',
    description: 'Repele las cinco invasiones.',
    icon: 'Achievement_Slayer_of_Worlds',
    group: 'eventos',
    tier: 'oro',
    requirement: { kind: 'invasionsCleared', amount: 5 },
    coins: 2_500_000,
  },

  // ---------------------------------------------------------------- evento lunar
  {
    id: 'cultist_down',
    name: 'Se rompe el cielo',
    description: 'Derrota al Cultista Lunatico en la puerta de la Mazmorra.',
    icon: 'Achievement_Obsessive_Devotion',
    group: 'lunar',
    tier: 'oro',
    requirement: { kind: 'bossDefeated', bossId: 'lunatic_cultist' },
    coins: 800_000,
  },
  {
    id: 'solar_down',
    name: 'Apagar el sol',
    description: 'Destruye el Pilar Solar.',
    icon: 'Achievement_Fear_The_Sun',
    group: 'lunar',
    tier: 'oro',
    requirement: { kind: 'bossDefeated', bossId: 'solar_pillar' },
    coins: 500_000,
  },
  {
    id: 'vortex_down',
    name: 'Calmar la tormenta',
    description: 'Destruye el Pilar del Vortice.',
    icon: 'Achievement_A_Rather_Blustery_Day',
    group: 'lunar',
    tier: 'oro',
    requirement: { kind: 'bossDefeated', bossId: 'vortex_pillar' },
    coins: 500_000,
  },
  {
    id: 'nebula_down',
    name: 'Sin colores',
    description: 'Destruye el Pilar de la Nebulosa.',
    icon: 'Achievement_Prismancer',
    group: 'lunar',
    tier: 'oro',
    requirement: { kind: 'bossDefeated', bossId: 'nebula_pillar' },
    coins: 500_000,
  },
  {
    id: 'stardust_down',
    name: 'Polvo eres',
    description: 'Destruye el Pilar del Polvo Estelar.',
    icon: 'Achievement_Into_Orbit',
    group: 'lunar',
    tier: 'oro',
    requirement: { kind: 'bossDefeated', bossId: 'stardust_pillar' },
    coins: 500_000,
  },
  {
    id: 'moon_lord_down',
    name: 'Cthulhu entero',
    description: 'Derrota al Senor de la Luna.',
    icon: 'Achievement_Champion_of_Terraria',
    group: 'lunar',
    tier: 'oro',
    requirement: { kind: 'bossDefeated', bossId: 'moon_lord' },
    coins: 4_000_000,
  },
  {
    id: 'lunar_farm',
    name: 'Cosechador de fragmentos',
    description: 'Recoge 300 fragmentos de polvo estelar.',
    icon: 'Achievement_Star_Destroyer',
    group: 'lunar',
    tier: 'oro',
    requirement: { kind: 'itemGathered', itemId: 'Stardust_Fragment', amount: 300 },
    coins: 900_000,
  },

  // ---------------------------------------------------------------- fortuna
  {
    id: 'treasure_hunter',
    name: 'Cazador de tesoros',
    description: 'Extrae un diamante.',
    icon: 'Achievement_Archaeologist',
    group: 'fortuna',
    tier: 'bronce',
    requirement: { kind: 'itemGathered', itemId: 'Diamond', amount: 1 },
    coins: 3000,
  },
  {
    id: 'ocean_visitor',
    name: 'Vista al mar',
    description: 'Visita el Oceano.',
    icon: 'Achievement_Sea_You_Later',
    group: 'fortuna',
    tier: 'bronce',
    requirement: { kind: 'zoneVisited', zoneId: 'ocean' },
    coins: 1500,
  },
  {
    id: 'rich',
    name: 'Forrado',
    description: 'Gana 1 moneda de platino en total.',
    icon: 'Achievement_Big_Booty',
    group: 'fortuna',
    tier: 'plata',
    requirement: { kind: 'coinsEarned', amount: 1_000_000 },
    coins: 20_000,
  },
  {
    id: 'crystal_mind',
    name: 'Mente de cristal',
    description: 'Recoge nueve cristales de mana: el maximo.',
    icon: 'Achievement_Star_Power',
    group: 'fortuna',
    tier: 'plata',
    requirement: { kind: 'itemGathered', itemId: 'Mana_Crystal', amount: 9 },
    coins: 50_000,
  },
  {
    id: 'dungeon_visitor',
    name: 'Ladrillo azul',
    description: 'Entra en la Mazmorra.',
    icon: 'Achievement_Dungeon_Heist',
    group: 'fortuna',
    tier: 'plata',
    requirement: { kind: 'zoneVisited', zoneId: 'dungeon' },
    coins: 20_000,
  },
  {
    id: 'loaded',
    name: 'Indecentemente rico',
    description: 'Gana 100 monedas de platino en total.',
    icon: 'Achievement_Feast_of_Midas',
    group: 'fortuna',
    tier: 'oro',
    requirement: { kind: 'coinsEarned', amount: 100_000_000 },
    coins: 2_000_000,
  },
  {
    id: 'moon_visitor',
    name: 'Un paseo por la Luna',
    description: 'Pisa la Luna. Solo se abre despues del Senor de la Luna.',
    icon: 'Achievement_A_Rare_Realm',
    group: 'fortuna',
    tier: 'oro',
    requirement: { kind: 'zoneVisited', zoneId: 'moon' },
    coins: 1_500_000,
  },
];
