import { ToolKind } from '../GameConstants';
import type { DropDef, ItemId } from '../items/ItemType';

/**
 * Un nodo recolectable: el bloque, arbol o veta que aparece en la zona y que se
 * rompe a clicks. Es el equivalente al "pokemon salvaje" de una ruta.
 */
export interface GatherNodeDef {
  id: string;
  /** Sprite y nombre se toman del item que representa el bloque. */
  itemId: ItemId;
  /** Vida del bloque: cuanto dano hay que meterle para romperlo. */
  health: number;
  /** Herramienta necesaria. */
  tool: ToolKind;
  /** Potencia minima de esa herramienta para poder danarlo. */
  toolPower: number;
  /** Botin garantizado o aleatorio al romperlo. */
  drops: DropDef[];
  /** Monedas que suelta, en cobre. */
  coins: [min: number, max: number];
  /** Peso relativo de aparicion dentro de la zona. */
  weight: number;
}

export const NodeList: Record<string, GatherNodeDef> = {
  // ================================================================ EVENTO LUNAR
  // Los otros tres fragmentos, para que la Luna sea la zona de farmeo del
  // postgame y no haga falta repetir el evento entero para rematar un conjunto.
  vortex_fragment_node: {
    id: 'vortex_fragment_node',
    itemId: 'Vortex_Fragment',
    health: 45000,
    tool: ToolKind.Pickaxe,
    toolPower: 200,
    drops: [{ itemId: 'Vortex_Fragment', min: 1, max: 2, chance: 1 }],
    coins: [24000, 48000],
    weight: 18,
  },
  nebula_fragment_node: {
    id: 'nebula_fragment_node',
    itemId: 'Nebula_Fragment',
    health: 45000,
    tool: ToolKind.Pickaxe,
    toolPower: 200,
    drops: [{ itemId: 'Nebula_Fragment', min: 1, max: 2, chance: 1 }],
    coins: [24000, 48000],
    weight: 18,
  },
  stardust_fragment_node: {
    id: 'stardust_fragment_node',
    itemId: 'Stardust_Fragment',
    health: 45000,
    tool: ToolKind.Pickaxe,
    toolPower: 200,
    drops: [{ itemId: 'Stardust_Fragment', min: 1, max: 2, chance: 1 }],
    coins: [24000, 48000],
    weight: 18,
  },

  // ================================================================ HARDMODE
  life_fruit_node: {
    id: 'life_fruit_node',
    itemId: 'Life_Fruit',
    health: 7000,
    tool: ToolKind.Pickaxe,
    toolPower: 150,
    drops: [{ itemId: 'Life_Fruit', min: 1, max: 1, chance: 1 }],
    coins: [2400, 4800],
    weight: 12,
  },
  pearlstone: {
    id: 'pearlstone',
    itemId: 'Pearlstone_Block',
    health: 1400,
    tool: ToolKind.Pickaxe,
    toolPower: 65,
    drops: [{ itemId: 'Pearlstone_Block', min: 2, max: 5, chance: 1 }],
    coins: [400, 800],
    weight: 24,
  },
  crystal_shard_node: {
    id: 'crystal_shard_node',
    itemId: 'Crystal_Shard',
    health: 1800,
    tool: ToolKind.Pickaxe,
    toolPower: 65,
    drops: [{ itemId: 'Crystal_Shard', min: 1, max: 3, chance: 1 }],
    coins: [900, 1800],
    weight: 18,
  },
  cobalt_vein: {
    id: 'cobalt_vein',
    itemId: 'Cobalt_Ore',
    health: 2600,
    tool: ToolKind.Pickaxe,
    toolPower: 100,
    drops: [{ itemId: 'Cobalt_Ore', min: 1, max: 3, chance: 1 }],
    coins: [1200, 2400],
    weight: 20,
  },
  palladium_vein: {
    id: 'palladium_vein',
    itemId: 'Palladium_Ore',
    health: 2800,
    tool: ToolKind.Pickaxe,
    toolPower: 100,
    drops: [{ itemId: 'Palladium_Ore', min: 1, max: 3, chance: 1 }],
    coins: [1300, 2600],
    weight: 18,
  },
  mythril_vein: {
    id: 'mythril_vein',
    itemId: 'Mythril_Ore',
    health: 4800,
    tool: ToolKind.Pickaxe,
    toolPower: 110,
    drops: [{ itemId: 'Mythril_Ore', min: 1, max: 3, chance: 1 }],
    coins: [2100, 4200],
    weight: 20,
  },
  orichalcum_vein: {
    id: 'orichalcum_vein',
    itemId: 'Orichalcum_Ore',
    health: 5000,
    tool: ToolKind.Pickaxe,
    toolPower: 110,
    drops: [{ itemId: 'Orichalcum_Ore', min: 1, max: 3, chance: 1 }],
    coins: [2300, 4600],
    weight: 18,
  },
  adamantite_vein: {
    id: 'adamantite_vein',
    itemId: 'Adamantite_Ore',
    health: 9000,
    tool: ToolKind.Pickaxe,
    toolPower: 150,
    drops: [{ itemId: 'Adamantite_Ore', min: 1, max: 3, chance: 1 }],
    coins: [3600, 7200],
    weight: 20,
  },
  titanium_vein: {
    id: 'titanium_vein',
    itemId: 'Titanium_Ore',
    health: 9500,
    tool: ToolKind.Pickaxe,
    toolPower: 150,
    drops: [{ itemId: 'Titanium_Ore', min: 1, max: 3, chance: 1 }],
    coins: [3900, 7800],
    weight: 18,
  },
  chlorophyte_vein: {
    id: 'chlorophyte_vein',
    itemId: 'Chlorophyte_Ore',
    health: 18000,
    tool: ToolKind.Pickaxe,
    toolPower: 200,
    drops: [{ itemId: 'Chlorophyte_Ore', min: 1, max: 3, chance: 1 }],
    coins: [6600, 13200],
    weight: 22,
  },
  // El ladrillo lihzahrd pedia 210 (la sierra-pico de Golem), y como es el unico
  // nodo del Templo el jugador entraba con el mejor pico que se puede fabricar
  // —el de clorofita, potencia 200— y no podia romper absolutamente nada: la
  // zona le ofrecia un bloque imposible, lo descartaba sola y le ofrecia otro
  // igual, en bucle. Ahora la clorofita entra justo, y la sierra-pico sigue
  // haciendo falta para la luminita.
  lihzahrd_brick_node: {
    id: 'lihzahrd_brick_node',
    itemId: 'Lihzahrd_Brick',
    health: 26000,
    tool: ToolKind.Pickaxe,
    toolPower: 200,
    drops: [{ itemId: 'Lihzahrd_Brick', min: 2, max: 5, chance: 1 }],
    coins: [2700, 5400],
    weight: 26,
  },
  luminite_vein: {
    id: 'luminite_vein',
    itemId: 'Luminite',
    health: 60000,
    tool: ToolKind.Pickaxe,
    toolPower: 210,
    drops: [{ itemId: 'Luminite', min: 1, max: 3, chance: 1 }],
    coins: [18000, 36000],
    weight: 24,
  },
  solar_fragment_node: {
    id: 'solar_fragment_node',
    itemId: 'Solar_Fragment',
    health: 45000,
    tool: ToolKind.Pickaxe,
    toolPower: 200,
    drops: [{ itemId: 'Solar_Fragment', min: 1, max: 2, chance: 1 }],
    coins: [24000, 48000],
    weight: 18,
  },
  // Vetas de los metales alternativos, mezcladas con las normales.
  tin_vein: {
    id: 'tin_vein',
    itemId: 'Tin_Ore',
    health: 48,
    tool: ToolKind.Pickaxe,
    toolPower: 35,
    drops: [{ itemId: 'Tin_Ore', min: 1, max: 3, chance: 1 }],
    coins: [6, 13],
    weight: 18,
  },
  lead_vein: {
    id: 'lead_vein',
    itemId: 'Lead_Ore',
    health: 75,
    tool: ToolKind.Pickaxe,
    toolPower: 35,
    drops: [{ itemId: 'Lead_Ore', min: 1, max: 3, chance: 1 }],
    coins: [11, 22],
    weight: 15,
  },
  tungsten_vein: {
    id: 'tungsten_vein',
    itemId: 'Tungsten_Ore',
    health: 118,
    tool: ToolKind.Pickaxe,
    toolPower: 40,
    drops: [{ itemId: 'Tungsten_Ore', min: 1, max: 3, chance: 1 }],
    coins: [20, 38],
    weight: 16,
  },
  platinum_vein: {
    id: 'platinum_vein',
    itemId: 'Platinum_Ore',
    health: 180,
    tool: ToolKind.Pickaxe,
    toolPower: 45,
    drops: [{ itemId: 'Platinum_Ore', min: 1, max: 3, chance: 1 }],
    coins: [34, 66],
    weight: 14,
  },

  // Oceano.
  coral_reef: {
    id: 'coral_reef',
    itemId: 'Coral',
    health: 55,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [
      { itemId: 'Coral', min: 1, max: 3, chance: 1 },
      { itemId: 'Starfish', min: 1, max: 1, chance: 0.2 },
    ],
    coins: [12, 26],
    weight: 22,
  },
  seashell_bed: {
    id: 'seashell_bed',
    itemId: 'Seashell',
    health: 45,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [
      { itemId: 'Seashell', min: 1, max: 2, chance: 1 },
      { itemId: 'Starfish', min: 1, max: 1, chance: 0.15 },
    ],
    coins: [15, 32],
    weight: 20,
  },
  // La colmena rompe el circulo de la Abeja Reina: sin miel ni cera fuera de
  // ella, su objeto de invocacion era imposible de fabricar.
  hive: {
    id: 'hive',
    itemId: 'Honey_Block',
    health: 200,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [
      { itemId: 'Honey_Block', min: 2, max: 5, chance: 1 },
      { itemId: 'Bee_Wax', min: 1, max: 2, chance: 0.3, affectedByLuck: true },
    ],
    coins: [40, 85],
    weight: 14,
  },
  fallen_star_node: {
    id: 'fallen_star_node',
    itemId: 'Fallen_Star',
    health: 60,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Fallen_Star', min: 1, max: 2, chance: 1 }],
    coins: [35, 75],
    weight: 6,
  },
  // ------------------------------------------------------------- desierto
  hardened_sand: {
    id: 'hardened_sand',
    itemId: 'Hardened_Sand_Block',
    health: 26,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Hardened_Sand_Block', min: 1, max: 3, chance: 1 }],
    coins: [3, 7],
    weight: 24,
  },
  sandstone: {
    id: 'sandstone',
    itemId: 'Sandstone_Block',
    health: 60,
    tool: ToolKind.Pickaxe,
    toolPower: 35,
    drops: [{ itemId: 'Sandstone_Block', min: 1, max: 3, chance: 1 }],
    coins: [6, 14],
    weight: 20,
  },
  cactus_patch: {
    id: 'cactus_patch',
    itemId: 'Cactus',
    health: 34,
    tool: ToolKind.Axe,
    toolPower: 30,
    drops: [{ itemId: 'Cactus', min: 2, max: 5, chance: 1 }],
    coins: [5, 11],
    weight: 18,
  },
  waterleaf_patch: {
    id: 'waterleaf_patch',
    itemId: 'Waterleaf',
    health: 40,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Waterleaf', min: 1, max: 2, chance: 1 }],
    coins: [18, 38],
    weight: 8,
  },
  amber_vein: {
    id: 'amber_vein',
    itemId: 'Amber',
    health: 190,
    tool: ToolKind.Pickaxe,
    toolPower: 40,
    drops: [{ itemId: 'Amber', min: 1, max: 2, chance: 1 }],
    coins: [70, 150],
    weight: 5,
  },
  silt: {
    id: 'silt',
    itemId: 'Silt_Block',
    health: 30,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [
      { itemId: 'Silt_Block', min: 1, max: 3, chance: 1 },
      { itemId: 'Copper_Ore', min: 1, max: 2, chance: 0.14, affectedByLuck: true },
      { itemId: 'Silver_Ore', min: 1, max: 1, chance: 0.05, affectedByLuck: true },
    ],
    coins: [4, 10],
    weight: 12,
  },

  // ------------------------------------------------------------- jungla
  mahogany_tree: {
    id: 'mahogany_tree',
    itemId: 'Rich_Mahogany',
    health: 130,
    tool: ToolKind.Axe,
    toolPower: 45,
    drops: [{ itemId: 'Rich_Mahogany', min: 2, max: 6, chance: 1 }],
    coins: [16, 34],
    weight: 20,
  },
  jungle_spore_patch: {
    id: 'jungle_spore_patch',
    itemId: 'Jungle_Spores',
    health: 110,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Jungle_Spores', min: 1, max: 2, chance: 1 }],
    coins: [30, 65],
    weight: 22,
  },
  vine_cluster: {
    id: 'vine_cluster',
    itemId: 'Vine',
    health: 80,
    tool: ToolKind.Axe,
    toolPower: 35,
    drops: [{ itemId: 'Vine', min: 1, max: 3, chance: 1 }],
    coins: [18, 40],
    weight: 18,
  },
  moonglow_patch: {
    id: 'moonglow_patch',
    itemId: 'Moonglow',
    health: 95,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Moonglow', min: 1, max: 2, chance: 1 }],
    coins: [25, 55],
    weight: 10,
  },
  jungle_rose_patch: {
    id: 'jungle_rose_patch',
    itemId: 'Jungle_Rose',
    health: 150,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Jungle_Rose', min: 1, max: 1, chance: 1 }],
    coins: [45, 95],
    weight: 4,
  },

  // ------------------------------------------------------------- nieve
  snow: {
    id: 'snow',
    itemId: 'Snow_Block',
    health: 20,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Snow_Block', min: 2, max: 5, chance: 1 }],
    coins: [2, 6],
    weight: 26,
  },
  ice: {
    id: 'ice',
    itemId: 'Ice_Block',
    health: 70,
    tool: ToolKind.Pickaxe,
    toolPower: 35,
    drops: [{ itemId: 'Ice_Block', min: 1, max: 3, chance: 1 }],
    coins: [7, 16],
    weight: 22,
  },
  boreal_tree: {
    id: 'boreal_tree',
    itemId: 'Boreal_Wood',
    health: 100,
    tool: ToolKind.Axe,
    toolPower: 40,
    drops: [{ itemId: 'Boreal_Wood', min: 2, max: 6, chance: 1 }],
    coins: [12, 26],
    weight: 20,
  },
  shiverthorn_patch: {
    id: 'shiverthorn_patch',
    itemId: 'Shiverthorn',
    health: 90,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Shiverthorn', min: 1, max: 2, chance: 1 }],
    coins: [22, 48],
    weight: 10,
  },
  slush: {
    id: 'slush',
    itemId: 'Slush_Block',
    health: 45,
    tool: ToolKind.Pickaxe,
    toolPower: 35,
    drops: [
      { itemId: 'Slush_Block', min: 1, max: 3, chance: 1 },
      { itemId: 'Iron_Ore', min: 1, max: 2, chance: 0.16, affectedByLuck: true },
      { itemId: 'Silver_Ore', min: 1, max: 1, chance: 0.08, affectedByLuck: true },
    ],
    coins: [8, 18],
    weight: 16,
  },

  // ------------------------------------------------------------- meteorito
  meteorite_vein: {
    id: 'meteorite_vein',
    itemId: 'Meteorite',
    health: 420,
    tool: ToolKind.Pickaxe,
    toolPower: 50,
    drops: [{ itemId: 'Meteorite', min: 1, max: 3, chance: 1 }],
    coins: [120, 240],
    weight: 30,
  },
  ash_from_impact: {
    id: 'ash_from_impact',
    itemId: 'Ash_Block',
    health: 60,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Ash_Block', min: 2, max: 5, chance: 1 }],
    coins: [10, 22],
    weight: 20,
  },

  // ------------------------------------------------------------- mazmorra
  blue_brick: {
    id: 'blue_brick',
    itemId: 'Blue_Brick',
    health: 300,
    tool: ToolKind.Pickaxe,
    toolPower: 55,
    drops: [
      { itemId: 'Blue_Brick', min: 1, max: 3, chance: 1 },
      { itemId: 'Golden_Key', min: 1, max: 1, chance: 0.05, affectedByLuck: true },
    ],
    coins: [45, 95],
    weight: 26,
  },
  bone_block: {
    id: 'bone_block',
    itemId: 'Bone_Block',
    health: 260,
    tool: ToolKind.Pickaxe,
    toolPower: 50,
    drops: [
      { itemId: 'Bone_Block', min: 1, max: 2, chance: 1 },
      { itemId: 'Bone', min: 1, max: 3, chance: 0.6 },
    ],
    coins: [40, 85],
    weight: 22,
  },

  // ------------------------------------------------------------- corrupcion
  deathweed_patch: {
    id: 'deathweed_patch',
    itemId: 'Deathweed',
    health: 140,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Deathweed', min: 1, max: 2, chance: 1 }],
    coins: [30, 65],
    weight: 10,
  },

  // ------------------------------------------------------------- infierno
  hellstone_vein: {
    id: 'hellstone_vein',
    itemId: 'Hellstone',
    health: 800,
    tool: ToolKind.Pickaxe,
    toolPower: 65,
    drops: [{ itemId: 'Hellstone', min: 1, max: 3, chance: 1 }],
    coins: [260, 520],
    weight: 26,
  },
  obsidian_chunk: {
    id: 'obsidian_chunk',
    itemId: 'Obsidian',
    health: 560,
    tool: ToolKind.Pickaxe,
    toolPower: 55,
    drops: [{ itemId: 'Obsidian', min: 1, max: 3, chance: 1 }],
    coins: [140, 280],
    weight: 22,
  },
  ash: {
    id: 'ash',
    itemId: 'Ash_Block',
    health: 120,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Ash_Block', min: 2, max: 6, chance: 1 }],
    coins: [20, 45],
    weight: 24,
  },
  fireblossom_patch: {
    id: 'fireblossom_patch',
    itemId: 'Fireblossom',
    health: 240,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Fireblossom', min: 1, max: 2, chance: 1 }],
    coins: [90, 190],
    weight: 8,
  },
  hellforge_ruin: {
    id: 'hellforge_ruin',
    itemId: 'Hellforge',
    health: 900,
    tool: ToolKind.Pickaxe,
    toolPower: 65,
    drops: [{ itemId: 'Hellforge', min: 1, max: 1, chance: 1 }],
    coins: [300, 600],
    weight: 4,
  },

  // ------------------------------------------------------------- subsuelo extra
  blinkroot_patch: {
    id: 'blinkroot_patch',
    itemId: 'Blinkroot',
    health: 55,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Blinkroot', min: 1, max: 2, chance: 1 }],
    coins: [16, 34],
    weight: 8,
  },
  dirt: {
    id: 'dirt',
    itemId: 'Dirt_Block',
    health: 8,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Dirt_Block', min: 1, max: 3, chance: 1 }],
    coins: [1, 3],
    weight: 30,
  },
  stone: {
    id: 'stone',
    itemId: 'Stone_Block',
    health: 18,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [
      { itemId: 'Stone_Block', min: 1, max: 3, chance: 1 },
      { itemId: 'Amethyst', min: 1, max: 1, chance: 0.02, affectedByLuck: true },
    ],
    coins: [2, 5],
    weight: 26,
  },
  tree: {
    id: 'tree',
    itemId: 'Wood',
    health: 30,
    tool: ToolKind.Axe,
    toolPower: 30,
    drops: [
      { itemId: 'Wood', min: 2, max: 5, chance: 1 },
      { itemId: 'Acorn', min: 1, max: 1, chance: 0.25 },
    ],
    coins: [3, 8],
    weight: 24,
  },
  ebonwood_tree: {
    id: 'ebonwood_tree',
    itemId: 'Ebonwood',
    health: 90,
    tool: ToolKind.Axe,
    toolPower: 45,
    drops: [{ itemId: 'Ebonwood', min: 2, max: 5, chance: 1 }],
    coins: [12, 25],
    weight: 18,
  },
  mushroom_patch: {
    id: 'mushroom_patch',
    itemId: 'Mushroom',
    health: 12,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Mushroom', min: 1, max: 2, chance: 1 }],
    coins: [4, 9],
    weight: 10,
  },
  daybloom_patch: {
    id: 'daybloom_patch',
    itemId: 'Daybloom',
    health: 14,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Daybloom', min: 1, max: 2, chance: 1 }],
    coins: [8, 16],
    weight: 6,
  },
  sand: {
    id: 'sand',
    itemId: 'Sand_Block',
    health: 10,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Sand_Block', min: 2, max: 4, chance: 1 }],
    coins: [1, 3],
    weight: 14,
  },
  cobweb: {
    id: 'cobweb',
    itemId: 'Cobweb',
    health: 10,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Cobweb', min: 2, max: 6, chance: 1 }],
    coins: [1, 2],
    weight: 12,
  },
  copper_vein: {
    id: 'copper_vein',
    itemId: 'Copper_Ore',
    health: 45,
    tool: ToolKind.Pickaxe,
    toolPower: 35,
    drops: [{ itemId: 'Copper_Ore', min: 1, max: 3, chance: 1 }],
    coins: [5, 12],
    weight: 22,
  },
  iron_vein: {
    id: 'iron_vein',
    itemId: 'Iron_Ore',
    health: 70,
    tool: ToolKind.Pickaxe,
    toolPower: 35,
    drops: [{ itemId: 'Iron_Ore', min: 1, max: 3, chance: 1 }],
    coins: [10, 20],
    weight: 18,
  },
  silver_vein: {
    id: 'silver_vein',
    itemId: 'Silver_Ore',
    health: 110,
    tool: ToolKind.Pickaxe,
    toolPower: 40,
    drops: [{ itemId: 'Silver_Ore', min: 1, max: 3, chance: 1 }],
    coins: [18, 34],
    weight: 14,
  },
  gold_vein: {
    id: 'gold_vein',
    itemId: 'Gold_Ore',
    health: 170,
    tool: ToolKind.Pickaxe,
    toolPower: 45,
    drops: [{ itemId: 'Gold_Ore', min: 1, max: 3, chance: 1 }],
    coins: [30, 60],
    weight: 12,
  },
  gem_amethyst: {
    id: 'gem_amethyst',
    itemId: 'Amethyst',
    health: 90,
    tool: ToolKind.Pickaxe,
    toolPower: 35,
    drops: [{ itemId: 'Amethyst', min: 1, max: 2, chance: 1 }],
    coins: [20, 45],
    weight: 8,
  },
  gem_topaz: {
    id: 'gem_topaz',
    itemId: 'Topaz',
    health: 110,
    tool: ToolKind.Pickaxe,
    toolPower: 35,
    drops: [{ itemId: 'Topaz', min: 1, max: 2, chance: 1 }],
    coins: [30, 60],
    weight: 7,
  },
  gem_sapphire: {
    id: 'gem_sapphire',
    itemId: 'Sapphire',
    health: 150,
    tool: ToolKind.Pickaxe,
    toolPower: 40,
    drops: [{ itemId: 'Sapphire', min: 1, max: 2, chance: 1 }],
    coins: [45, 90],
    weight: 6,
  },
  gem_emerald: {
    id: 'gem_emerald',
    itemId: 'Emerald',
    health: 190,
    tool: ToolKind.Pickaxe,
    toolPower: 45,
    drops: [{ itemId: 'Emerald', min: 1, max: 2, chance: 1 }],
    coins: [60, 120],
    weight: 5,
  },
  gem_ruby: {
    id: 'gem_ruby',
    itemId: 'Ruby',
    health: 240,
    tool: ToolKind.Pickaxe,
    toolPower: 45,
    drops: [{ itemId: 'Ruby', min: 1, max: 2, chance: 1 }],
    coins: [90, 180],
    weight: 4,
  },
  gem_diamond: {
    id: 'gem_diamond',
    itemId: 'Diamond',
    health: 320,
    tool: ToolKind.Pickaxe,
    toolPower: 55,
    drops: [{ itemId: 'Diamond', min: 1, max: 1, chance: 1 }],
    coins: [150, 300],
    weight: 3,
  },
  // Al 2% de peso y solo en Cavernas hacian falta cientos de nodos para las 15
  // que exige el Muro de Carne. Ahora aparece en casi todo el subsuelo.
  life_crystal_node: {
    id: 'life_crystal_node',
    itemId: 'Life_Crystal',
    health: 300,
    tool: ToolKind.Pickaxe,
    toolPower: 40,
    drops: [{ itemId: 'Life_Crystal', min: 1, max: 1, chance: 1 }],
    coins: [80, 160],
    weight: 7,
  },
  mana_crystal_node: {
    id: 'mana_crystal_node',
    itemId: 'Fallen_Star',
    health: 90,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Fallen_Star', min: 1, max: 3, chance: 1 }],
    coins: [40, 90],
    weight: 6,
  },
  ebonstone: {
    id: 'ebonstone',
    itemId: 'Ebonstone_Block',
    health: 260,
    tool: ToolKind.Pickaxe,
    toolPower: 65,
    drops: [{ itemId: 'Ebonstone_Block', min: 1, max: 3, chance: 1 }],
    coins: [25, 50],
    weight: 20,
  },
  demonite_vein: {
    id: 'demonite_vein',
    itemId: 'Demonite_Ore',
    health: 340,
    tool: ToolKind.Pickaxe,
    toolPower: 55,
    drops: [{ itemId: 'Demonite_Ore', min: 1, max: 3, chance: 1 }],
    coins: [60, 120],
    weight: 12,
  },
  vile_mushroom_patch: {
    id: 'vile_mushroom_patch',
    itemId: 'Vile_Mushroom',
    health: 120,
    tool: ToolKind.Pickaxe,
    toolPower: 0,
    drops: [{ itemId: 'Vile_Mushroom', min: 1, max: 2, chance: 1 }],
    coins: [30, 60],
    weight: 14,
  },
};

export const getNode = (id: string): GatherNodeDef => {
  const node = NodeList[id];
  if (!node) throw new Error(`Nodo desconocido: ${id}`);
  return node;
};
