import type { DropDef } from '../items/ItemType';

/**
 * Enemigos normales de zona. A diferencia de los jefes, no devuelven dano: la
 * zona es farmeo seguro, igual que las rutas de pokeclicker.
 */
export interface EnemyDef {
  id: string;
  name: string;
  /** Sprite descargado en public/assets/enemies. */
  sprite: string;
  health: number;
  drops: DropDef[];
  coins: [min: number, max: number];
  weight: number;
}

export const EnemyList: Record<string, EnemyDef> = {
  // ================================================================ EVENTOS
  // La fauna de las cinco invasiones. Solo aparece mientras su evento esta
  // activo: el pool de la zona lo sustituye Invasions mientras dura.

  // ---------------------------------------------------------------- ejercito de duendes
  goblin_peon: {
    id: 'goblin_peon',
    name: 'Peon duende',
    sprite: 'Goblin_Peon',
    health: 340,
    drops: [
      { itemId: 'Tattered_Cloth', min: 1, max: 1, chance: 0.2, affectedByLuck: true },
    ],
    coins: [140, 300],
    weight: 26,
  },
  goblin_thief: {
    id: 'goblin_thief',
    name: 'Ladron duende',
    sprite: 'Goblin_Thief',
    health: 420,
    drops: [
      { itemId: 'Tattered_Cloth', min: 1, max: 2, chance: 0.25, affectedByLuck: true },
    ],
    coins: [200, 420],
    weight: 20,
  },
  goblin_warrior: {
    id: 'goblin_warrior',
    name: 'Guerrero duende',
    sprite: 'Goblin_Warrior',
    health: 620,
    drops: [
      { itemId: 'Tattered_Cloth', min: 1, max: 2, chance: 0.3, affectedByLuck: true },
    ],
    coins: [280, 560],
    weight: 22,
  },
  goblin_archer: {
    id: 'goblin_archer',
    name: 'Arquero duende',
    sprite: 'Goblin_Archer',
    health: 520,
    drops: [
      { itemId: 'Tattered_Cloth', min: 1, max: 2, chance: 0.25, affectedByLuck: true },
    ],
    coins: [240, 500],
    weight: 20,
  },
  goblin_sorcerer: {
    id: 'goblin_sorcerer',
    name: 'Hechicero duende',
    sprite: 'Goblin_Sorcerer',
    health: 700,
    drops: [
      { itemId: 'Tattered_Cloth', min: 1, max: 2, chance: 0.3, affectedByLuck: true },
      { itemId: 'Shadowflame_Knife', min: 1, max: 1, chance: 0.05, affectedByLuck: true },
    ],
    coins: [360, 720],
    weight: 12,
  },
  goblin_summoner: {
    id: 'goblin_summoner',
    name: 'Invocador duende',
    sprite: 'Goblin_Summoner',
    health: 2600,
    drops: [
      { itemId: 'Tattered_Cloth', min: 3, max: 6, chance: 1 },
      { itemId: 'Shadowflame_Bow', min: 1, max: 1, chance: 0.25, affectedByLuck: true },
      { itemId: 'Shadowflame_Knife', min: 1, max: 1, chance: 0.25, affectedByLuck: true },
    ],
    coins: [2000, 4000],
    weight: 4,
  },

  // ---------------------------------------------------------------- eclipse solar
  swamp_thing: {
    id: 'swamp_thing',
    name: 'Cosa del pantano',
    sprite: 'Swamp_Thing',
    health: 4200,
    drops: [
      { itemId: 'Solar_Tablet_Fragment', min: 1, max: 1, chance: 0.06, affectedByLuck: true },
    ],
    coins: [3200, 6400],
    weight: 22,
  },
  frankenstein: {
    id: 'frankenstein',
    name: 'Frankenstein',
    sprite: 'Frankenstein',
    health: 4600,
    drops: [
      { itemId: 'Solar_Tablet_Fragment', min: 1, max: 1, chance: 0.06, affectedByLuck: true },
    ],
    coins: [3400, 6800],
    weight: 22,
  },
  vampire: {
    id: 'vampire',
    name: 'Vampiro',
    sprite: 'Vampire',
    health: 6000,
    drops: [
      { itemId: 'Broken_Bat_Wing', min: 1, max: 1, chance: 0.12, affectedByLuck: true },
      { itemId: 'Solar_Tablet_Fragment', min: 1, max: 1, chance: 0.08, affectedByLuck: true },
    ],
    coins: [4800, 9600],
    weight: 16,
  },
  fritz: {
    id: 'fritz',
    name: 'Fritz',
    sprite: 'Fritz',
    health: 3800,
    drops: [
      { itemId: 'Solar_Tablet_Fragment', min: 1, max: 1, chance: 0.05, affectedByLuck: true },
    ],
    coins: [3000, 6000],
    weight: 20,
  },
  creature_from_the_deep: {
    id: 'creature_from_the_deep',
    name: 'Criatura de las profundidades',
    sprite: 'Creature_from_the_Deep',
    health: 4400,
    drops: [
      { itemId: 'Solar_Tablet_Fragment', min: 1, max: 1, chance: 0.06, affectedByLuck: true },
    ],
    coins: [3400, 6800],
    weight: 18,
  },
  the_possessed: {
    id: 'the_possessed',
    name: 'El poseido',
    sprite: 'The_Possessed',
    health: 5200,
    drops: [
      { itemId: 'Solar_Tablet_Fragment', min: 1, max: 1, chance: 0.07, affectedByLuck: true },
    ],
    coins: [4000, 8000],
    weight: 16,
  },
  eyezor: {
    id: 'eyezor',
    name: 'Ojazo',
    sprite: 'Eyezor',
    health: 5000,
    drops: [
      { itemId: 'Solar_Tablet_Fragment', min: 1, max: 1, chance: 0.07, affectedByLuck: true },
    ],
    coins: [3800, 7600],
    weight: 16,
  },
  butcher: {
    id: 'butcher',
    name: 'Carnicero',
    sprite: 'Butcher',
    health: 7000,
    drops: [
      { itemId: 'Solar_Tablet_Fragment', min: 1, max: 2, chance: 0.1, affectedByLuck: true },
      { itemId: 'Broken_Hero_Sword', min: 1, max: 1, chance: 0.05, affectedByLuck: true },
    ],
    coins: [5600, 11200],
    weight: 12,
  },
  deadly_sphere: {
    id: 'deadly_sphere',
    name: 'Esfera mortal',
    sprite: 'Deadly_Sphere',
    health: 6400,
    drops: [
      { itemId: 'Solar_Tablet_Fragment', min: 1, max: 1, chance: 0.08, affectedByLuck: true },
    ],
    coins: [5000, 10000],
    weight: 12,
  },
  dr_man_fly: {
    id: 'dr_man_fly',
    name: 'Dr. Mosca',
    sprite: 'Dr._Man_Fly',
    health: 7600,
    drops: [
      { itemId: 'Solar_Tablet_Fragment', min: 1, max: 2, chance: 0.1, affectedByLuck: true },
      { itemId: 'Broken_Hero_Sword', min: 1, max: 1, chance: 0.06, affectedByLuck: true },
    ],
    coins: [6000, 12000],
    weight: 10,
  },
  nailhead: {
    id: 'nailhead',
    name: 'Cabeza de clavo',
    sprite: 'Nailhead',
    health: 6800,
    drops: [
      { itemId: 'Solar_Tablet_Fragment', min: 1, max: 1, chance: 0.08, affectedByLuck: true },
    ],
    coins: [5200, 10400],
    weight: 12,
  },
  psycho: {
    id: 'psycho',
    name: 'Psicopata',
    sprite: 'Psycho',
    health: 6200,
    drops: [
      { itemId: 'Solar_Tablet_Fragment', min: 1, max: 1, chance: 0.08, affectedByLuck: true },
      { itemId: 'Death_Sickle', min: 1, max: 1, chance: 0.03, affectedByLuck: true },
    ],
    coins: [5000, 10000],
    weight: 12,
  },
  reaper: {
    id: 'reaper',
    name: 'Segador',
    sprite: 'Reaper',
    health: 8400,
    drops: [
      { itemId: 'Solar_Tablet_Fragment', min: 1, max: 2, chance: 0.12, affectedByLuck: true },
      { itemId: 'Death_Sickle', min: 1, max: 1, chance: 0.06, affectedByLuck: true },
    ],
    coins: [7000, 14000],
    weight: 8,
  },

  // ---------------------------------------------------------------- legion de escarcha
  mister_stabby: {
    id: 'mister_stabby',
    name: 'Senor Punzante',
    sprite: 'Mister_Stabby',
    health: 3000,
    drops: [
      { itemId: 'Snow_Block', min: 2, max: 5, chance: 0.5 },
    ],
    coins: [2400, 4800],
    weight: 24,
  },
  snowman_gangsta: {
    id: 'snowman_gangsta',
    name: 'Muneco gangster',
    sprite: 'Snowman_Gangsta',
    health: 3400,
    drops: [
      { itemId: 'Snow_Block', min: 2, max: 5, chance: 0.5 },
    ],
    coins: [2600, 5200],
    weight: 24,
  },
  snow_balla: {
    id: 'snow_balla',
    name: 'Bolanieves',
    sprite: 'Snow_Balla',
    health: 3200,
    drops: [
      { itemId: 'Snow_Block', min: 2, max: 5, chance: 0.5 },
      { itemId: 'Blizzard_Staff', min: 1, max: 1, chance: 0.02, affectedByLuck: true },
    ],
    coins: [2500, 5000],
    weight: 22,
  },

  // ---------------------------------------------------------------- luna de escarcha
  flocko: {
    id: 'flocko',
    name: 'Copito',
    sprite: 'Flocko',
    health: 8000,
    drops: [
      { itemId: 'Ice_Block', min: 2, max: 5, chance: 0.6 },
    ],
    coins: [7000, 14000],
    weight: 22,
  },
  gingerbread_man: {
    id: 'gingerbread_man',
    name: 'Hombre de jengibre',
    sprite: 'Gingerbread_Man',
    health: 9000,
    drops: [
      { itemId: 'Ectoplasm', min: 1, max: 2, chance: 0.2, affectedByLuck: true },
    ],
    coins: [7600, 15200],
    weight: 22,
  },
  zombie_elf: {
    id: 'zombie_elf',
    name: 'Elfo zombi',
    sprite: 'Zombie_Elf',
    health: 10000,
    drops: [
      { itemId: 'Ectoplasm', min: 1, max: 2, chance: 0.2, affectedByLuck: true },
    ],
    coins: [8200, 16400],
    weight: 20,
  },
  elf_archer: {
    id: 'elf_archer',
    name: 'Elfo arquero',
    sprite: 'Elf_Archer',
    health: 11000,
    drops: [
      { itemId: 'Ectoplasm', min: 1, max: 2, chance: 0.22, affectedByLuck: true },
    ],
    coins: [8800, 17600],
    weight: 18,
  },
  elf_copter: {
    id: 'elf_copter',
    name: 'Elicoptero elfo',
    sprite: 'Elf_Copter',
    health: 13000,
    drops: [
      { itemId: 'Ectoplasm', min: 1, max: 3, chance: 0.25, affectedByLuck: true },
    ],
    coins: [10000, 20000],
    weight: 14,
  },
  present_mimic: {
    id: 'present_mimic',
    name: 'Mimico regalo',
    sprite: 'Present_Mimic',
    health: 18000,
    drops: [
      { itemId: 'Ectoplasm', min: 2, max: 4, chance: 0.4, affectedByLuck: true },
      { itemId: 'Christmas_Tree_Sword', min: 1, max: 1, chance: 0.04, affectedByLuck: true },
    ],
    coins: [16000, 32000],
    weight: 8,
  },
  krampus: {
    id: 'krampus',
    name: 'Krampus',
    sprite: 'Krampus',
    health: 24000,
    drops: [
      { itemId: 'Ectoplasm', min: 3, max: 6, chance: 0.6, affectedByLuck: true },
      { itemId: 'Elf_Melter', min: 1, max: 1, chance: 0.06, affectedByLuck: true },
    ],
    coins: [22000, 44000],
    weight: 6,
  },
  everscream: {
    id: 'everscream',
    name: 'Grito eterno',
    sprite: 'Everscream',
    health: 40000,
    drops: [
      { itemId: 'Razorpine', min: 1, max: 1, chance: 0.15, affectedByLuck: true },
      { itemId: 'Ectoplasm', min: 4, max: 8, chance: 1 },
    ],
    coins: [40000, 80000],
    weight: 3,
  },
  santa_nk1: {
    id: 'santa_nk1',
    name: 'Santa-NK1',
    sprite: 'Santa-NK1',
    health: 48000,
    drops: [
      { itemId: 'Chain_Gun', min: 1, max: 1, chance: 0.12, affectedByLuck: true },
      { itemId: 'Elf_Melter', min: 1, max: 1, chance: 0.12, affectedByLuck: true },
      { itemId: 'Ectoplasm', min: 4, max: 8, chance: 1 },
    ],
    coins: [48000, 96000],
    weight: 3,
  },

  // ---------------------------------------------------------------- locura marciana
  martian_drone: {
    id: 'martian_drone',
    name: 'Dron marciano',
    sprite: 'Martian_Drone',
    health: 11000,
    drops: [
      { itemId: 'Martian_Conduit_Plating', min: 1, max: 3, chance: 0.4 },
    ],
    coins: [11000, 22000],
    weight: 22,
  },
  scutlix_gunner: {
    id: 'scutlix_gunner',
    name: 'Jinete de scutlix',
    sprite: 'Scutlix_Gunner',
    health: 13000,
    drops: [
      { itemId: 'Martian_Conduit_Plating', min: 1, max: 3, chance: 0.4 },
    ],
    coins: [12000, 24000],
    weight: 20,
  },
  ray_gunner: {
    id: 'ray_gunner',
    name: 'Artillero de rayos',
    sprite: 'Ray_Gunner',
    health: 14000,
    drops: [
      { itemId: 'Martian_Conduit_Plating', min: 1, max: 3, chance: 0.45 },
    ],
    coins: [13000, 26000],
    weight: 20,
  },
  gigazapper: {
    id: 'gigazapper',
    name: 'Gigazapper',
    sprite: 'Gigazapper',
    health: 15000,
    drops: [
      { itemId: 'Martian_Conduit_Plating', min: 1, max: 4, chance: 0.45 },
    ],
    coins: [14000, 28000],
    weight: 18,
  },
  martian_engineer: {
    id: 'martian_engineer',
    name: 'Ingeniero marciano',
    sprite: 'Martian_Engineer',
    health: 16000,
    drops: [
      { itemId: 'Martian_Conduit_Plating', min: 2, max: 4, chance: 0.5 },
    ],
    coins: [15000, 30000],
    weight: 16,
  },
  martian_walker: {
    id: 'martian_walker',
    name: 'Caminante marciano',
    sprite: 'Martian_Walker',
    health: 22000,
    drops: [
      { itemId: 'Martian_Conduit_Plating', min: 2, max: 5, chance: 0.6 },
      { itemId: 'Xenopopper', min: 1, max: 1, chance: 0.04, affectedByLuck: true },
    ],
    coins: [22000, 44000],
    weight: 10,
  },
  martian_officer: {
    id: 'martian_officer',
    name: 'Oficial marciano',
    sprite: 'Martian_Officer',
    health: 20000,
    drops: [
      { itemId: 'Martian_Conduit_Plating', min: 2, max: 5, chance: 0.55 },
      { itemId: 'Xeno_Staff', min: 1, max: 1, chance: 0.04, affectedByLuck: true },
    ],
    coins: [20000, 40000],
    weight: 12,
  },

  // ================================================================ EVENTO LUNAR
  // La fauna de los cuatro pilares. Tienen la vida ajustada para que los mil
  // bichos de cada escudo se hagan en un rato largo, no en una tarde: con el
  // equipo de Golem caen en algo menos de un segundo cada uno.

  // ---------------------------------------------------------------- cultistas
  lunatic_devotee: {
    id: 'lunatic_devotee',
    name: 'Devoto lunatico',
    sprite: 'Lunatic_Devotee',
    health: 5200,
    drops: [{ itemId: 'Ectoplasm', min: 1, max: 2, chance: 0.3, affectedByLuck: true }],
    coins: [4000, 8000],
    weight: 20,
  },
  cultist_archer: {
    id: 'cultist_archer',
    name: 'Arquero cultista',
    sprite: 'Cultist_Archer',
    health: 4800,
    drops: [{ itemId: 'Ectoplasm', min: 1, max: 2, chance: 0.3, affectedByLuck: true }],
    coins: [4000, 8000],
    weight: 20,
  },

  // ---------------------------------------------------------------- pilar solar
  drakomire: {
    id: 'drakomire',
    name: 'Drakomire',
    sprite: 'Drakomire',
    health: 5200,
    drops: [{ itemId: 'Solar_Fragment', min: 1, max: 2, chance: 0.2, affectedByLuck: true }],
    coins: [6000, 12000],
    weight: 22,
  },
  corite: {
    id: 'corite',
    name: 'Corita',
    sprite: 'Corite',
    health: 4400,
    drops: [{ itemId: 'Solar_Fragment', min: 1, max: 2, chance: 0.2, affectedByLuck: true }],
    coins: [5500, 11000],
    weight: 24,
  },
  sroller: {
    id: 'sroller',
    name: 'Rodador',
    sprite: 'Sroller',
    health: 4800,
    drops: [{ itemId: 'Solar_Fragment', min: 1, max: 2, chance: 0.2, affectedByLuck: true }],
    coins: [5800, 11600],
    weight: 22,
  },
  crawltipede: {
    id: 'crawltipede',
    name: 'Reptapies',
    sprite: 'Crawltipede',
    health: 6400,
    drops: [{ itemId: 'Solar_Fragment', min: 2, max: 3, chance: 0.25, affectedByLuck: true }],
    coins: [8000, 16000],
    weight: 12,
  },

  // ---------------------------------------------------------------- pilar del vortice
  storm_diver: {
    id: 'storm_diver',
    name: 'Buceador de tormenta',
    sprite: 'Storm_Diver',
    health: 4600,
    drops: [{ itemId: 'Vortex_Fragment', min: 1, max: 2, chance: 0.2, affectedByLuck: true }],
    coins: [5600, 11200],
    weight: 24,
  },
  vortexian: {
    id: 'vortexian',
    name: 'Vortexiano',
    sprite: 'Vortexian',
    health: 4200,
    drops: [{ itemId: 'Vortex_Fragment', min: 1, max: 2, chance: 0.2, affectedByLuck: true }],
    coins: [5400, 10800],
    weight: 22,
  },
  alien_queen: {
    id: 'alien_queen',
    name: 'Reina alienigena',
    sprite: 'Alien_Queen',
    health: 6000,
    drops: [{ itemId: 'Vortex_Fragment', min: 2, max: 3, chance: 0.25, affectedByLuck: true }],
    coins: [7600, 15200],
    weight: 14,
  },

  // ---------------------------------------------------------------- pilar de la nebulosa
  nebula_floater_lunar: {
    id: 'nebula_floater_lunar',
    name: 'Flotador de nebulosa',
    sprite: 'Nebula_Floater',
    health: 4400,
    drops: [{ itemId: 'Nebula_Fragment', min: 1, max: 2, chance: 0.2, affectedByLuck: true }],
    coins: [5400, 10800],
    weight: 24,
  },
  brain_suckler: {
    id: 'brain_suckler',
    name: 'Chupacerebros',
    sprite: 'Brain_Suckler',
    health: 3800,
    drops: [{ itemId: 'Nebula_Fragment', min: 1, max: 2, chance: 0.2, affectedByLuck: true }],
    coins: [5000, 10000],
    weight: 24,
  },
  predictor: {
    id: 'predictor',
    name: 'Predictor',
    sprite: 'Predictor',
    health: 4600,
    drops: [{ itemId: 'Nebula_Fragment', min: 1, max: 2, chance: 0.2, affectedByLuck: true }],
    coins: [5600, 11200],
    weight: 20,
  },
  evolution_beast: {
    id: 'evolution_beast',
    name: 'Bestia de la evolucion',
    sprite: 'Evolution_Beast',
    health: 5600,
    drops: [{ itemId: 'Nebula_Fragment', min: 2, max: 3, chance: 0.25, affectedByLuck: true }],
    coins: [7000, 14000],
    weight: 14,
  },

  // ---------------------------------------------------------------- pilar del polvo estelar
  star_cell: {
    id: 'star_cell',
    name: 'Celula estelar',
    sprite: 'Star_Cell',
    health: 3600,
    drops: [{ itemId: 'Stardust_Fragment', min: 1, max: 2, chance: 0.2, affectedByLuck: true }],
    coins: [5000, 10000],
    weight: 24,
  },
  flow_invader: {
    id: 'flow_invader',
    name: 'Invasor del flujo',
    sprite: 'Flow_Invader',
    health: 4800,
    drops: [{ itemId: 'Stardust_Fragment', min: 1, max: 2, chance: 0.2, affectedByLuck: true }],
    coins: [5600, 11200],
    weight: 20,
  },
  twinkle_popper: {
    id: 'twinkle_popper',
    name: 'Estallacentellas',
    sprite: 'Twinkle_Popper',
    health: 4200,
    drops: [{ itemId: 'Stardust_Fragment', min: 1, max: 2, chance: 0.2, affectedByLuck: true }],
    coins: [5200, 10400],
    weight: 20,
  },
  milkyway_weaver: {
    id: 'milkyway_weaver',
    name: 'Tejedor de la via lactea',
    sprite: 'Milkyway_Weaver',
    health: 5400,
    drops: [{ itemId: 'Stardust_Fragment', min: 2, max: 3, chance: 0.25, affectedByLuck: true }],
    coins: [6800, 13600],
    weight: 16,
  },
  stargazer: {
    id: 'stargazer',
    name: 'Observador de estrellas',
    sprite: 'Stargazer',
    health: 4000,
    drops: [{ itemId: 'Stardust_Fragment', min: 1, max: 2, chance: 0.2, affectedByLuck: true }],
    coins: [5200, 10400],
    weight: 18,
  },

  // ================================================================ HARDMODE
  pixie: {
    id: 'pixie',
    name: 'Hada',
    sprite: 'Pixie',
    health: 2600,
    drops: [
      { itemId: 'Pixie_Dust', min: 1, max: 3, chance: 0.7 },
      { itemId: 'Soul_of_Light', min: 1, max: 2, chance: 0.35, affectedByLuck: true },
    ],
    coins: [900, 1800],
    weight: 24,
  },
  unicorn: {
    id: 'unicorn',
    name: 'Unicornio',
    sprite: 'Unicorn',
    health: 4200,
    drops: [
      { itemId: 'Unicorn_Horn', min: 1, max: 1, chance: 0.3, affectedByLuck: true },
      { itemId: 'Soul_of_Light', min: 1, max: 2, chance: 0.35, affectedByLuck: true },
    ],
    coins: [1500, 3000],
    weight: 18,
  },
  gastropod: {
    id: 'gastropod',
    name: 'Gasteropodo',
    sprite: 'Gastropod',
    health: 3200,
    drops: [{ itemId: 'Soul_of_Light', min: 1, max: 2, chance: 0.3, affectedByLuck: true }],
    coins: [1200, 2400],
    weight: 20,
  },
  illuminant_bat: {
    id: 'illuminant_bat',
    name: 'Murcielago iluminado',
    sprite: 'Illuminant_Bat',
    health: 2800,
    drops: [{ itemId: 'Soul_of_Light', min: 1, max: 1, chance: 0.28, affectedByLuck: true }],
    coins: [1000, 2000],
    weight: 22,
  },
  chaos_elemental: {
    id: 'chaos_elemental',
    name: 'Elemental del caos',
    sprite: 'Chaos_Elemental',
    health: 4800,
    drops: [
      { itemId: 'Soul_of_Light', min: 1, max: 3, chance: 0.4, affectedByLuck: true },
      { itemId: 'Light_Shard', min: 1, max: 1, chance: 0.06, affectedByLuck: true },
    ],
    coins: [1900, 3800],
    weight: 12,
  },
  enchanted_sword: {
    id: 'enchanted_sword',
    name: 'Espada encantada',
    sprite: 'Enchanted_Sword',
    health: 3600,
    drops: [{ itemId: 'Broken_Hero_Sword', min: 1, max: 1, chance: 0.05, affectedByLuck: true }],
    coins: [1400, 2800],
    weight: 10,
  },
  wyvern: {
    id: 'wyvern',
    name: 'Guiverno',
    sprite: 'Wyvern',
    health: 7000,
    drops: [{ itemId: 'Soul_of_Flight', min: 2, max: 5, chance: 0.8, affectedByLuck: true }],
    coins: [2800, 5600],
    weight: 8,
  },
  corruptor: {
    id: 'corruptor',
    name: 'Corruptor',
    sprite: 'Corruptor',
    health: 4400,
    drops: [
      { itemId: 'Soul_of_Night', min: 1, max: 2, chance: 0.38, affectedByLuck: true },
      { itemId: 'Rotten_Chunk', min: 2, max: 5, chance: 0.4 },
    ],
    coins: [1700, 3400],
    weight: 22,
  },
  clinger: {
    id: 'clinger',
    name: 'Aferrador',
    sprite: 'Clinger',
    health: 5000,
    drops: [
      { itemId: 'Soul_of_Night', min: 1, max: 2, chance: 0.35, affectedByLuck: true },
      { itemId: 'Dark_Shard', min: 1, max: 1, chance: 0.06, affectedByLuck: true },
    ],
    coins: [1900, 3800],
    weight: 18,
  },
  slimer: {
    id: 'slimer',
    name: 'Slimer',
    sprite: 'Slimer',
    health: 3400,
    drops: [
      { itemId: 'Gel', min: 10, max: 25, chance: 1 },
      { itemId: 'Soul_of_Night', min: 1, max: 1, chance: 0.25, affectedByLuck: true },
    ],
    coins: [1300, 2600],
    weight: 20,
  },
  armored_skeleton: {
    id: 'armored_skeleton',
    name: 'Esqueleto acorazado',
    sprite: 'Armored_Skeleton',
    health: 5600,
    drops: [
      { itemId: 'Bone', min: 5, max: 12, chance: 0.7 },
      { itemId: 'Soul_of_Night', min: 1, max: 1, chance: 0.2, affectedByLuck: true },
    ],
    coins: [2100, 4200],
    weight: 16,
  },
  possessed_armor: {
    id: 'possessed_armor',
    name: 'Armadura poseida',
    sprite: 'Possessed_Armor',
    health: 6000,
    drops: [{ itemId: 'Soul_of_Night', min: 1, max: 2, chance: 0.3, affectedByLuck: true }],
    coins: [2300, 4600],
    weight: 14,
  },
  mimic: {
    id: 'mimic',
    name: 'Mimico',
    sprite: 'Mimic',
    health: 9000,
    drops: [
      { itemId: 'Spectre_Boots', min: 1, max: 1, chance: 0.05, affectedByLuck: true },
      { itemId: 'Cross_Necklace', min: 1, max: 1, chance: 0.04, affectedByLuck: true },
      { itemId: 'Star_Veil', min: 1, max: 1, chance: 0.03, affectedByLuck: true },
      { itemId: 'Soul_of_Night', min: 2, max: 4, chance: 0.5, affectedByLuck: true },
    ],
    coins: [5000, 10000],
    weight: 5,
  },
  werewolf: {
    id: 'werewolf',
    name: 'Hombre lobo',
    sprite: 'Werewolf',
    health: 5200,
    drops: [{ itemId: 'Soul_of_Night', min: 1, max: 1, chance: 0.2, affectedByLuck: true }],
    coins: [2000, 4000],
    weight: 14,
  },
  arapaima: {
    id: 'arapaima',
    name: 'Arapaima',
    sprite: 'Arapaima',
    health: 7200,
    drops: [{ itemId: 'Shark_Fin', min: 1, max: 3, chance: 0.5 }],
    coins: [2600, 5200],
    weight: 18,
  },
  giant_tortoise: {
    id: 'giant_tortoise',
    name: 'Tortuga gigante',
    sprite: 'Giant_Tortoise',
    health: 8800,
    drops: [{ itemId: 'Jungle_Spores', min: 3, max: 8, chance: 0.6 }],
    coins: [3200, 6400],
    weight: 16,
  },
  moss_hornet: {
    id: 'moss_hornet',
    name: 'Avispon de musgo',
    sprite: 'Moss_Hornet',
    health: 6400,
    drops: [{ itemId: 'Stinger', min: 2, max: 6, chance: 0.7 }],
    coins: [2400, 4800],
    weight: 22,
  },
  angler_fish: {
    id: 'angler_fish',
    name: 'Pez abisal',
    sprite: 'Angler_Fish',
    health: 6800,
    drops: [{ itemId: 'Shark_Fin', min: 1, max: 2, chance: 0.4 }],
    coins: [2500, 5000],
    weight: 14,
  },
  rune_wizard: {
    id: 'rune_wizard',
    name: 'Mago rúnico',
    sprite: 'Rune_Wizard',
    health: 11000,
    drops: [{ itemId: 'Ectoplasm', min: 1, max: 3, chance: 0.6, affectedByLuck: true }],
    coins: [7000, 14000],
    weight: 6,
  },
  diabolist: {
    id: 'diabolist',
    name: 'Diabolista',
    sprite: 'Diabolist',
    health: 9500,
    drops: [
      { itemId: 'Ectoplasm', min: 1, max: 2, chance: 0.5, affectedByLuck: true },
      { itemId: 'Death_Sickle', min: 1, max: 1, chance: 0.02, affectedByLuck: true },
    ],
    coins: [5200, 10400],
    weight: 12,
  },
  blue_armored_bones: {
    id: 'blue_armored_bones',
    name: 'Huesos acorazados azules',
    sprite: 'Blue_Armored_Bones',
    health: 10000,
    drops: [
      { itemId: 'Bone', min: 8, max: 18, chance: 0.7 },
      { itemId: 'Ectoplasm', min: 1, max: 1, chance: 0.25, affectedByLuck: true },
    ],
    coins: [4800, 9600],
    weight: 16,
  },
  lihzahrd: {
    id: 'lihzahrd',
    name: 'Lihzahrd',
    sprite: 'Lihzahrd',
    health: 16000,
    drops: [{ itemId: 'Lihzahrd_Brick', min: 2, max: 6, chance: 0.6 }],
    coins: [9000, 18000],
    weight: 22,
  },
  flying_snake: {
    id: 'flying_snake',
    name: 'Serpiente voladora',
    sprite: 'Flying_Snake',
    health: 14000,
    drops: [{ itemId: 'Lihzahrd_Brick', min: 1, max: 4, chance: 0.5 }],
    coins: [8000, 16000],
    weight: 20,
  },
  selenian: {
    id: 'selenian',
    name: 'Seleniano',
    sprite: 'Selenian',
    health: 40000,
    drops: [{ itemId: 'Solar_Fragment', min: 1, max: 2, chance: 0.4, affectedByLuck: true }],
    coins: [26000, 52000],
    weight: 20,
  },
  nebula_floater: {
    id: 'nebula_floater',
    name: 'Flotador de nebulosa',
    sprite: 'Nebula_Floater',
    health: 36000,
    drops: [{ itemId: 'Solar_Fragment', min: 1, max: 1, chance: 0.3, affectedByLuck: true }],
    coins: [24000, 48000],
    weight: 20,
  },
  // Cavernas profundas.
  tim: {
    id: 'tim',
    name: 'Tim',
    sprite: 'Tim',
    health: 300,
    drops: [
      { itemId: 'Amethyst', min: 1, max: 2, chance: 0.3 },
      { itemId: 'Band_of_Regeneration', min: 1, max: 1, chance: 0.03, affectedByLuck: true },
    ],
    coins: [90, 180],
    weight: 8,
  },
  giant_bat: {
    id: 'giant_bat',
    name: 'Murcielago gigante',
    sprite: 'Giant_Bat',
    health: 210,
    drops: [{ itemId: 'Lens', min: 1, max: 2, chance: 0.15, affectedByLuck: true }],
    coins: [40, 85],
    weight: 20,
  },
  salamander: {
    id: 'salamander',
    name: 'Salamandra',
    sprite: 'Salamander',
    health: 260,
    drops: [{ itemId: 'Blinkroot', min: 1, max: 2, chance: 0.35 }],
    coins: [55, 115],
    weight: 16,
  },
  mother_slime: {
    id: 'mother_slime',
    name: 'Slime madre',
    sprite: 'Mother_Slime',
    health: 150,
    drops: [
      { itemId: 'Gel', min: 4, max: 9, chance: 1 },
      { itemId: 'Copper_Ore', min: 1, max: 3, chance: 0.2 },
    ],
    coins: [28, 60],
    weight: 18,
  },

  // Oceano.
  shark: {
    id: 'shark',
    name: 'Tiburon',
    sprite: 'Shark',
    health: 420,
    drops: [
      { itemId: 'Shark_Fin', min: 1, max: 2, chance: 0.5 },
      { itemId: 'Shark_Tooth_Necklace', min: 1, max: 1, chance: 0.04, affectedByLuck: true },
    ],
    coins: [110, 230],
    weight: 12,
  },
  squid: {
    id: 'squid',
    name: 'Calamar',
    sprite: 'Squid',
    health: 180,
    drops: [{ itemId: 'Coral', min: 1, max: 2, chance: 0.3 }],
    coins: [35, 75],
    weight: 20,
  },
  green_jellyfish: {
    id: 'green_jellyfish',
    name: 'Medusa verde',
    sprite: 'Green_Jellyfish',
    health: 200,
    drops: [{ itemId: 'Flipper', min: 1, max: 1, chance: 0.04, affectedByLuck: true }],
    coins: [42, 88],
    weight: 16,
  },
  pink_jellyfish: {
    id: 'pink_jellyfish',
    name: 'Medusa rosa',
    sprite: 'Pink_Jellyfish',
    health: 240,
    drops: [{ itemId: 'Diving_Helmet', min: 1, max: 1, chance: 0.03, affectedByLuck: true }],
    coins: [50, 105],
    weight: 14,
  },
  // ------------------------------------------------------------- desierto
  sand_slime: {
    id: 'sand_slime',
    name: 'Slime de arena',
    sprite: 'Sand_Slime',
    health: 95,
    drops: [
      { itemId: 'Gel', min: 2, max: 5, chance: 1 },
      { itemId: 'Sand_Block', min: 2, max: 6, chance: 0.7 },
    ],
    coins: [16, 34],
    weight: 20,
  },
  crab: {
    id: 'crab',
    name: 'Cangrejo',
    sprite: 'Crab',
    health: 140,
    drops: [{ itemId: 'Seashell', min: 1, max: 2, chance: 0.35 }],
    coins: [26, 55],
    weight: 20,
  },

  // ------------------------------------------------------------- jungla
  jungle_slime: {
    id: 'jungle_slime',
    name: 'Slime de jungla',
    sprite: 'Jungle_Slime',
    health: 190,
    drops: [
      { itemId: 'Gel', min: 3, max: 7, chance: 1 },
      { itemId: 'Jungle_Spores', min: 1, max: 1, chance: 0.15 },
    ],
    coins: [45, 95],
    weight: 24,
  },
  spiked_jungle_slime: {
    id: 'spiked_jungle_slime',
    name: 'Slime de jungla con pinchos',
    sprite: 'Spiked_Jungle_Slime',
    health: 260,
    drops: [
      { itemId: 'Stinger', min: 1, max: 2, chance: 0.4 },
      { itemId: 'Vine', min: 1, max: 2, chance: 0.3 },
    ],
    coins: [65, 130],
    weight: 16,
  },
  piranha: {
    id: 'piranha',
    name: 'Piraña',
    sprite: 'Piranha',
    health: 210,
    drops: [{ itemId: 'Shark_Tooth_Necklace', min: 1, max: 1, chance: 0.02, affectedByLuck: true }],
    coins: [50, 105],
    weight: 16,
  },
  snatcher: {
    id: 'snatcher',
    name: 'Atrapador',
    sprite: 'Snatcher',
    health: 240,
    drops: [
      { itemId: 'Vine', min: 1, max: 3, chance: 0.5 },
      { itemId: "Nature's_Gift", min: 1, max: 1, chance: 0.02, affectedByLuck: true },
    ],
    coins: [60, 125],
    weight: 14,
  },

  // ------------------------------------------------------------- nieve
  ice_slime: {
    id: 'ice_slime',
    name: 'Slime de hielo',
    sprite: 'Ice_Slime',
    health: 120,
    drops: [
      { itemId: 'Gel', min: 2, max: 5, chance: 1 },
      { itemId: 'Ice_Block', min: 1, max: 3, chance: 0.6 },
    ],
    coins: [22, 46],
    weight: 24,
  },
  zombie_eskimo: {
    id: 'zombie_eskimo',
    name: 'Zombi esquimal',
    sprite: 'Zombie_Eskimo',
    health: 160,
    drops: [
      { itemId: 'Shackle', min: 1, max: 1, chance: 0.04, affectedByLuck: true },
      { itemId: 'Rotten_Chunk', min: 1, max: 2, chance: 0.2 },
    ],
    coins: [30, 62],
    weight: 20,
  },
  undead_viking: {
    id: 'undead_viking',
    name: 'Vikingo no muerto',
    sprite: 'Undead_Viking',
    health: 240,
    drops: [
      { itemId: 'Silver_Ore', min: 2, max: 5, chance: 0.4 },
      { itemId: 'Shiny_Red_Balloon', min: 1, max: 1, chance: 0.02, affectedByLuck: true },
    ],
    coins: [55, 115],
    weight: 14,
  },
  wolf: {
    id: 'wolf',
    name: 'Lobo',
    sprite: 'Wolf',
    health: 200,
    drops: [{ itemId: 'Feral_Claws', min: 1, max: 1, chance: 0.02, affectedByLuck: true }],
    coins: [45, 92],
    weight: 16,
  },
  ice_bat: {
    id: 'ice_bat',
    name: 'Murcielago de hielo',
    sprite: 'Ice_Bat',
    health: 140,
    drops: [{ itemId: 'Lens', min: 1, max: 1, chance: 0.1, affectedByLuck: true }],
    coins: [26, 55],
    weight: 20,
  },
  snow_flinx: {
    id: 'snow_flinx',
    name: 'Flinx de nieve',
    sprite: 'Snow_Flinx',
    health: 130,
    drops: [{ itemId: 'Snow_Block', min: 3, max: 8, chance: 0.8 }],
    coins: [24, 50],
    weight: 18,
  },

  // ------------------------------------------------------------- meteorito
  meteor_head: {
    id: 'meteor_head',
    name: 'Cabeza de meteorito',
    sprite: 'Meteor_Head',
    health: 380,
    drops: [{ itemId: 'Meteorite', min: 1, max: 3, chance: 0.45, affectedByLuck: true }],
    coins: [140, 290],
    weight: 30,
  },

  // ------------------------------------------------------------- mazmorra
  angry_bones: {
    id: 'angry_bones',
    name: 'Huesos furiosos',
    sprite: 'Angry_Bones',
    health: 420,
    drops: [
      { itemId: 'Bone', min: 2, max: 5, chance: 0.6 },
      { itemId: 'Muramasa', min: 1, max: 1, chance: 0.015, affectedByLuck: true },
    ],
    coins: [120, 250],
    weight: 26,
  },
  dark_caster: {
    id: 'dark_caster',
    name: 'Lanzador oscuro',
    sprite: 'Dark_Caster',
    health: 480,
    drops: [
      { itemId: 'Bone', min: 1, max: 3, chance: 0.5 },
      { itemId: 'Water_Bolt', min: 1, max: 1, chance: 0.02, affectedByLuck: true },
      { itemId: 'Rocket_Boots', min: 1, max: 1, chance: 0.025, affectedByLuck: true },
    ],
    coins: [140, 290],
    weight: 18,
  },
  cursed_skull: {
    id: 'cursed_skull',
    name: 'Craneo maldito',
    sprite: 'Cursed_Skull',
    health: 400,
    drops: [
      { itemId: 'Bone', min: 1, max: 3, chance: 0.45 },
      { itemId: 'Blue_Moon', min: 1, max: 1, chance: 0.015, affectedByLuck: true },
    ],
    coins: [115, 240],
    weight: 20,
  },
  dungeon_slime: {
    id: 'dungeon_slime',
    name: 'Slime de mazmorra',
    sprite: 'Dungeon_Slime',
    health: 360,
    drops: [
      { itemId: 'Gel', min: 5, max: 10, chance: 1 },
      { itemId: 'Golden_Key', min: 1, max: 1, chance: 0.2, affectedByLuck: true },
    ],
    coins: [100, 210],
    weight: 16,
  },
  doctor_bones: {
    id: 'doctor_bones',
    name: 'Doctor Huesos',
    sprite: 'Doctor_Bones',
    health: 620,
    drops: [
      { itemId: 'Bone', min: 4, max: 8, chance: 0.8 },
      { itemId: 'Cobalt_Shield', min: 1, max: 1, chance: 0.06, affectedByLuck: true },
    ],
    coins: [220, 450],
    weight: 6,
  },

  // ------------------------------------------------------------- infierno
  fire_imp: {
    id: 'fire_imp',
    name: 'Diablillo de fuego',
    sprite: 'Fire_Imp',
    health: 700,
    drops: [{ itemId: 'Imp_Staff', min: 1, max: 1, chance: 0.02, affectedByLuck: true }],
    coins: [260, 540],
    weight: 22,
  },
  lava_slime: {
    id: 'lava_slime',
    name: 'Slime de lava',
    sprite: 'Lava_Slime',
    health: 620,
    drops: [
      { itemId: 'Gel', min: 8, max: 16, chance: 1 },
      { itemId: 'Obsidian', min: 1, max: 2, chance: 0.3 },
    ],
    coins: [230, 480],
    weight: 24,
  },
  demon: {
    id: 'demon',
    name: 'Demonio',
    sprite: 'Demon',
    health: 880,
    drops: [
      { itemId: 'Obsidian', min: 1, max: 3, chance: 0.4 },
      { itemId: 'Magma_Stone', min: 1, max: 1, chance: 0.03, affectedByLuck: true },
    ],
    coins: [340, 700],
    weight: 20,
  },
  hellbat: {
    id: 'hellbat',
    name: 'Murcielago infernal',
    sprite: 'Hellbat',
    health: 540,
    drops: [{ itemId: 'Lens', min: 1, max: 2, chance: 0.2, affectedByLuck: true }],
    coins: [200, 420],
    weight: 22,
  },
  bone_serpent: {
    id: 'bone_serpent',
    name: 'Serpiente de hueso',
    sprite: 'Bone_Serpent',
    health: 1100,
    drops: [
      { itemId: 'Bone', min: 5, max: 12, chance: 0.8 },
      { itemId: 'Lava_Charm', min: 1, max: 1, chance: 0.03, affectedByLuck: true },
    ],
    coins: [420, 860],
    weight: 12,
  },
  voodoo_demon: {
    id: 'voodoo_demon',
    name: 'Demonio vudu',
    sprite: 'Voodoo_Demon',
    health: 980,
    drops: [{ itemId: 'Guide_Voodoo_Doll', min: 1, max: 1, chance: 0.2, affectedByLuck: true }],
    coins: [380, 780],
    weight: 8,
  },
  green_slime: {
    id: 'green_slime',
    name: 'Slime verde',
    sprite: 'Green_Slime',
    health: 25,
    drops: [
      { itemId: 'Gel', min: 1, max: 3, chance: 1 },
      { itemId: 'Slime_Staff', min: 1, max: 1, chance: 0.004, affectedByLuck: true },
    ],
    coins: [3, 8],
    weight: 30,
  },
  blue_slime: {
    id: 'blue_slime',
    name: 'Slime azul',
    sprite: 'Blue_Slime',
    health: 45,
    drops: [{ itemId: 'Gel', min: 2, max: 4, chance: 1 }],
    coins: [6, 14],
    weight: 22,
  },
  purple_slime: {
    id: 'purple_slime',
    name: 'Slime morado',
    sprite: 'Purple_Slime',
    health: 90,
    drops: [
      { itemId: 'Gel', min: 3, max: 6, chance: 1 },
      { itemId: 'Amethyst', min: 1, max: 1, chance: 0.05, affectedByLuck: true },
    ],
    coins: [14, 30],
    weight: 12,
  },
  yellow_slime: {
    id: 'yellow_slime',
    name: 'Slime amarillo',
    sprite: 'Yellow_Slime',
    health: 70,
    drops: [{ itemId: 'Gel', min: 2, max: 5, chance: 1 }],
    coins: [10, 24],
    weight: 14,
  },
  demon_eye: {
    id: 'demon_eye',
    name: 'Ojo demoniaco',
    sprite: 'Demon_Eye',
    health: 60,
    drops: [
      { itemId: 'Lens', min: 1, max: 1, chance: 0.33, affectedByLuck: true },
      { itemId: 'Black_Lens', min: 1, max: 1, chance: 0.02, affectedByLuck: true },
    ],
    coins: [12, 26],
    weight: 18,
  },
  zombie: {
    id: 'zombie',
    name: 'Zombi',
    sprite: 'Zombie',
    health: 55,
    drops: [
      { itemId: 'Shackle', min: 1, max: 1, chance: 0.03, affectedByLuck: true },
      { itemId: 'Rotten_Chunk', min: 1, max: 1, chance: 0.12 },
    ],
    coins: [10, 22],
    weight: 18,
  },
  vulture: {
    id: 'vulture',
    name: 'Buitre',
    sprite: 'Vulture',
    health: 65,
    drops: [{ itemId: 'Cactus', min: 1, max: 2, chance: 0.4 }],
    coins: [12, 25],
    weight: 12,
  },
  cave_bat: {
    id: 'cave_bat',
    name: 'Murcielago de cueva',
    sprite: 'Cave_Bat',
    health: 80,
    drops: [{ itemId: 'Lens', min: 1, max: 1, chance: 0.08, affectedByLuck: true }],
    coins: [14, 30],
    weight: 24,
  },
  giant_worm: {
    id: 'giant_worm',
    name: 'Gusano gigante',
    sprite: 'Giant_Worm',
    health: 70,
    drops: [{ itemId: 'Worm_Tooth', min: 1, max: 2, chance: 0.6 }],
    coins: [10, 24],
    weight: 20,
  },
  skeleton: {
    id: 'skeleton',
    name: 'Esqueleto',
    sprite: 'Skeleton',
    health: 130,
    drops: [
      { itemId: 'Bone', min: 1, max: 2, chance: 0.5 },
      { itemId: 'Grappling_Hook', min: 1, max: 1, chance: 0.02, affectedByLuck: true },
    ],
    coins: [25, 55],
    weight: 22,
  },
  undead_miner: {
    id: 'undead_miner',
    name: 'Minero no muerto',
    sprite: 'Undead_Miner',
    health: 180,
    drops: [
      { itemId: 'Copper_Ore', min: 2, max: 5, chance: 0.5 },
      { itemId: 'Hermes_Boots', min: 1, max: 1, chance: 0.02, affectedByLuck: true },
      { itemId: 'Depth_Meter', min: 1, max: 1, chance: 0.03, affectedByLuck: true },
    ],
    coins: [45, 90],
    weight: 10,
  },
  man_eater: {
    id: 'man_eater',
    name: 'Devoraplantas',
    sprite: 'Man_Eater',
    health: 160,
    drops: [
      { itemId: 'Mushroom', min: 1, max: 3, chance: 0.5 },
      { itemId: 'Lucky_Horseshoe', min: 1, max: 1, chance: 0.02, affectedByLuck: true },
    ],
    coins: [35, 70],
    weight: 12,
  },
  antlion: {
    id: 'antlion',
    name: 'Hormiga leon',
    sprite: 'Antlion',
    health: 140,
    drops: [{ itemId: 'Antlion_Mandible', min: 1, max: 2, chance: 0.45 }],
    coins: [30, 60],
    weight: 12,
  },
  eater_of_souls: {
    id: 'eater_of_souls',
    name: 'Devorador de almas',
    sprite: 'Eater_of_Souls',
    health: 220,
    drops: [
      { itemId: 'Rotten_Chunk', min: 1, max: 2, chance: 0.5 },
      { itemId: 'Shadow_Scale', min: 1, max: 2, chance: 0.14, affectedByLuck: true },
      { itemId: 'Demonite_Ore', min: 1, max: 2, chance: 0.05, affectedByLuck: true },
    ],
    coins: [60, 120],
    weight: 26,
  },
  devourer: {
    id: 'devourer',
    name: 'Devorador',
    sprite: 'Devourer',
    health: 260,
    drops: [
      { itemId: 'Rotten_Chunk', min: 1, max: 3, chance: 0.55 },
      { itemId: 'Worm_Tooth', min: 1, max: 3, chance: 0.4 },
      { itemId: 'Shadow_Scale', min: 1, max: 2, chance: 0.12, affectedByLuck: true },
    ],
    coins: [70, 140],
    weight: 22,
  },
  corrupt_slime: {
    id: 'corrupt_slime',
    name: 'Slime corrupto',
    sprite: 'Corrupt_Slime',
    health: 300,
    drops: [
      { itemId: 'Gel', min: 4, max: 8, chance: 1 },
      { itemId: 'Vile_Mushroom', min: 1, max: 1, chance: 0.15 },
    ],
    coins: [80, 160],
    weight: 16,
  },
  hornet: {
    id: 'hornet',
    name: 'Avispon',
    sprite: 'Hornet',
    health: 200,
    drops: [
      { itemId: 'Vile_Mushroom', min: 1, max: 1, chance: 0.1 },
      { itemId: 'Bee_Wax', min: 1, max: 1, chance: 0.18, affectedByLuck: true },
      { itemId: 'Stinger', min: 1, max: 2, chance: 0.35 },
    ],
    coins: [55, 110],
    weight: 10,
  },
  goblin_scout: {
    id: 'goblin_scout',
    name: 'Explorador goblin',
    sprite: 'Goblin_Scout',
    health: 240,
    drops: [
      { itemId: 'Silk', min: 1, max: 2, chance: 0.3 },
      { itemId: 'Cloud_in_a_Bottle', min: 1, max: 1, chance: 0.02, affectedByLuck: true },
    ],
    coins: [90, 180],
    weight: 6,
  },
  blue_jellyfish: {
    id: 'blue_jellyfish',
    name: 'Medusa azul',
    sprite: 'Blue_Jellyfish',
    health: 160,
    drops: [
      { itemId: 'Glass', min: 1, max: 2, chance: 0.3 },
      { itemId: 'Coral', min: 1, max: 2, chance: 0.25 },
    ],
    coins: [30, 65],
    weight: 18,
  },
};

export const getEnemy = (id: string): EnemyDef => {
  const enemy = EnemyList[id];
  if (!enemy) throw new Error(`Enemigo desconocido: ${id}`);
  return enemy;
};
